class ChoreDataStructure:
    ID = "id"
    PEOPLE = "people"
    NAME = "name"
    START_TIME = "startTime"
    REMINDER_INTERVAL_MINUTES = "reminderIntervalMinutes"
    STATUS = "status"
    REPLY_TO_MESSAGE_ID = "replyToMessageId"
    LAST_SENT = "lastSent"
    SNOOZE_DURATION = "snoozeDuration"
    IS_DAILY_CHORE = "isDailyChore"
    WEEK = "week"
    DAY = "day"